version: '2'

services:
  nginx-nv:
    build:
      context: ./nginx
    volumes:
      # - '${API_SOURCE_PATH}:/app' # default docker volume sync
      # - '${API_SOURCE_PATH}:/app:cached' # docker caching layer
      - nv-sync:/app:nocopy # macOS: docker-sync
    ports:
      - '${API_WEB_PORT}:80'
    depends_on:
      - api-nv

  api-nv:
    build:
      context: ./api
    volumes:
      # - '${API_SOURCE_PATH}:/app' # default docker volume sync
      # - '${API_SOURCE_PATH}:/app:cached' # docker caching layer
      - nv-sync:/app:nocopy # macOS: docker-sync

  db-nv:
    image: mysql:5.7
    volumes:
      - mysql-nv:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nv
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
# macOS: for docker-sync
volumes:
  nv-sync:
    external: true
  mysql-nv:
